config/routes.rb
Rails.application.routes.draw do
  resources :places

  get 'mine' => 'places#mine'

  devise_for :users 

  devise_scope :user do 
    get 'sign_out' => 'user/sessions#destroy' 
  end

  root 'places#index'
  

end

app/models/place.rb
class Place < ActiveRecord::Base

	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :places

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  def mine
    @places = current_user.places
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
    @place.users << current_user
  end

  # GET /places/1/edit
  def edit
    if @place.users.include? current_user
      flash[:notice] = "This is your place"
    else
      flash[:notice] = "This is NOT your place"
      redirect_to :mine


    end

  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    @place.users << current_user

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :address1, :address2, :address3, :address4, :city, :state, :zip, :phone1, :phone2, :phone3, :phone4, :manager, :comments)
    end
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
    # session[:current_user_id] = nil
    # flash[:notice] = "You've logged out"
    # redirect_to root_url
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Manage Library Info Prototype" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= nav_bar :fixed => :top, :brand => "Manage Library Info Prototype", :responsive => true do %>
    <%= menu_group do %>
        <%= menu_item "All Places", places_path %>
        <%= menu_divider %>
        <%= drop_down "Places" do %>
            <%= menu_item "Sign in", "/users/sign_in" %>
            <%= menu_item "All Places", places_path %>
        <% end %>  
    <% end %>

    <%= menu_group :pull => :right do %>
        <% if current_user %>
          <%= menu_item "My Places", "/mine" %>
          <%= menu_item "Sign Out", "/sign_out" %>
        <% else %>
            <%= menu_item "Sign In", "/users/sign_in" %>
            <% end -%>
        <% end %>
    <% end %>


    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">FakeSrp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Sign Out", "/sign_out"  %></li>
            <li><%= link_to "Log in", "/users/sign_in"  %></li>
            <li><%= link_to "All Places", "/places"  %></li>
            <li><%= link_to "My Places", "/mine"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        

      <footer>
        <p>&copy; Devin K. Farmer 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place, :html => { :class => "form-horizontal place" } do |f| %>

  <% if @place.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :address1, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address1, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address1) %>
  </div>
  <div class="form-group">
    <%= f.label :address2, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address2, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address2) %>
  </div>
  <div class="form-group">
    <%= f.label :address3, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address3, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address3) %>
  </div>
  <div class="form-group">
    <%= f.label :address4, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address4, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address4) %>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
    <%=f.error_span(:city) %>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :state, :class => 'form-control' %>
    </div>
    <%=f.error_span(:state) %>
  </div>
  <div class="form-group">
    <%= f.label :zip, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :zip, :class => 'form-control' %>
    </div>
    <%=f.error_span(:zip) %>
  </div>
  <div class="form-group">
    <%= f.label :phone1, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone1, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone1) %>
  </div>
  <div class="form-group">
    <%= f.label :phone2, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone2, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone2) %>
  </div>
  <div class="form-group">
    <%= f.label :phone3, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone3, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone3) %>
  </div>
  <div class="form-group">
    <%= f.label :phone4, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone4, :class => 'form-control' %>
    </div>
    <%=f.error_span(:phone4) %>
  </div>
  <div class="form-group">
    <%= f.label :manager, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :manager, :class => 'form-control' %>
    </div>
    <%=f.error_span(:manager) %>
  </div>
  <div class="form-group">
    <%= f.label :comments, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :comments, :class => 'form-control' %>
    </div>
    <%=f.error_span(:comments) %>
  </div>
  <% if @place.users.include? current_user %>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                places_path, :class => 'btn btn-default' %>
    </div>
  </div>
  <% end %>

<% end %>

app/views/places/edit.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/places/index.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_place_path,
            :class => 'btn btn-primary' %>
</div>

  
    <% @places.each do |place| %>
    <div class="col-xs-4" style="outline: 2px solid-black;">
    <table class="table table-striped">
    <tbody>
      <% if place.name %>
        <tr><td>Name</td><td><%= link_to place.name, place_path(place) %></td></tr>
      <% end %> 
      <% if place.address1 != "" %>
        <tr><td>Address</td><td><%= place.address1 %></td></tr>
      <% end %>  
      <% if place.address2 != "" %>
        <tr><td></td><td><%= place.address2 %></td></tr>
      <% end %>  
      <% if place.address3 != "" %>
        <tr><td></td><td><%= place.address3 %></td></tr>
      <% end %> 
      <% if place.address4 != "" %>
        <tr><td></td><td><%= place.address4 %></td></tr>
      <% end %>
      <% if place.city != "" %>
        <tr><td>City</td><td><%= place.city %></td></tr>
      <% end %> 
      <% if place.state != "" %>
        <tr><td>State</td><td><%= place.state %></td></tr>
      <% end %> 
      <% if place.zip != "" %>
        <tr><td>Zip Code</td><td><%= place.zip %></td></tr>
      <% end %> 
      <% if place.phone1 != "" %>
        <tr><td>Phone</td><td><%= place.phone1 %></td></tr>
      <% end %> 
      <% if place.phone2 != "" %>
        <tr><td>Phone</td><td><%= place.phone2 %></td></tr>
      <% end %> 
      <% if place.phone3 != "" %>
        <tr><td>Phone</td><td><%= place.phone3 %></td></tr>
      <% end %> 
      <% if place.phone4 != "" %>
        <tr><td>Phone</td><td><%= place.phone4 %></td></tr>
      <% end %>  
      <% if place.manager != "" %>
        <tr><td>Manager</td><td><%= place.manager %></td></tr>
      <% end %>
        </tbody>
</table>
</div>
    <% end %>

app/views/places/mine.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => "My " << model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address1) %></th>
      <th><%= model_class.human_attribute_name(:address2) %></th>
      <th><%= model_class.human_attribute_name(:address3) %></th>
      <th><%= model_class.human_attribute_name(:address4) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:zip) %></th>
      <th><%= model_class.human_attribute_name(:phone1) %></th>
      <th><%= model_class.human_attribute_name(:phone2) %></th>
      <th><%= model_class.human_attribute_name(:phone3) %></th>
      <th><%= model_class.human_attribute_name(:phone4) %></th>
      <th><%= model_class.human_attribute_name(:manager) %></th>
      <th><%= model_class.human_attribute_name(:comments) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.name, place_path(place) %></td>
        <td><%= place.address1 %></td>
        <td><%= place.address2 %></td>
        <td><%= place.address3 %></td>
        <td><%= place.address4 %></td>
        <td><%= place.city %></td>
        <td><%= place.state %></td>
        <td><%= place.zip %></td>
        <td><%= place.phone1 %></td>
        <td><%= place.phone2 %></td>
        <td><%= place.phone3 %></td>
        <td><%= place.phone4 %></td>
        <td><%= place.manager %></td>
        <td><%= place.comments %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_place_path(place), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      place_path(place),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_place_path,
            :class => 'btn btn-primary' %>

app/views/places/new.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/places/show.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @place.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address1) %>:</strong></dt>
  <dd><%= @place.address1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address2) %>:</strong></dt>
  <dd><%= @place.address2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address3) %>:</strong></dt>
  <dd><%= @place.address3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address4) %>:</strong></dt>
  <dd><%= @place.address4 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @place.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @place.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zip) %>:</strong></dt>
  <dd><%= @place.zip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone1) %>:</strong></dt>
  <dd><%= @place.phone1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone2) %>:</strong></dt>
  <dd><%= @place.phone2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone3) %>:</strong></dt>
  <dd><%= @place.phone3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone4) %>:</strong></dt>
  <dd><%= @place.phone4 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:manager) %>:</strong></dt>
  <dd><%= @place.manager %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comments) %>:</strong></dt>
  <dd><%= @place.comments %></dd>
</dl>
<% if @place.users.include? current_user %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              places_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_place_path(@place), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              place_path(@place),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
              <% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>